In [3]:
import pandas as pd

df = pd.read_csv(r"D:\AI-Customer-Support-Intelligence-Platform\data\raw\synthetic_it_support_tickets.csv")

print(df.shape)
df.head()

(100000, 20)

,ticket_id,created_at,customer_id,customer_segment,channel,product_area,issue_type,priority,status,sla_plan,initial_message,agent_first_reply,resolution_summary,resolution_time_hours,reopened,customer_sentiment,csat_score,has_attachment,platform,region
0,TCKT_000001,2024-01-31T05:14:27,CUST_00861,individual,email,data_export,account_access,low,resolved,standard,I cannot log in; the system says my password i...,Sorry to hear you're having trouble accessing ...,Reset account credentials and confirmed succes...,36.53,0,very_negative,1,0,android,EU
1,TCKT_000002,2024-10-20T06:15:49,CUST_00770,individual,in_app,billing,security_concern,medium,closed_no_action,standard,I noticed a suspicious login on my account.,We take security very seriously. Our team is r...,Ticket closed without further action after no ...,238.32,0,neutral,3,0,web,NaN
2,TCKT_000003,2024-06-18T21:35:54,CUST_02559,small_business,chat,api_integration,bug,low,in_progress,standard,The api integration feature is not saving my c...,Thanks for reporting this bug. We will look in...,NaN,NaN,0,neutral,3,0,android,MEA
3,TCKT_000004,2025-12-25T15:59:52,CUST_03557,education,chat,analytics_dashboard,account_access,medium,in_progress,standard,I cannot log in; the system says my password i...,Sorry to hear you're having trouble accessing ...,NaN,NaN,0,positive,5,1,android,LATAM
4,TCKT_000005,2023-08-27T16:08:33,CUST_09556,enterprise,phone_transcript,login_auth,billing_problem,low,resolved,gold,My invoice amount is incorrect compared to the...,Thanks for reaching out about the billing issu...,Adjusted the invoice and issued a refund where...,61.32,0,very_negative,2,0,web,NaN

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   ticket_id              100000 non-null  str
 1   created_at             100000 non-null  str
 2   customer_id            100000 non-null  str
 3   customer_segment       100000 non-null  str
 4   channel                100000 non-null  str
 5   product_area           100000 non-null  str
 6   issue_type             100000 non-null  str
 7   priority               100000 non-null  str
 8   status                 100000 non-null  str
 9   sla_plan               100000 non-null  str
 10  initial_message        100000 non-null  str
 11  agent_first_reply      100000 non-null  str
 12  resolution_summary     60113 non-null   str
 13  resolution_time_hours  60113 non-null   float64
 14  reopened               100000 non-null  int64
 15  customer_sentiment     100000 non-null  str
 16  csat_score             100000 non-null  int64
 17  has_attachment         100000 non-null  int64
 18  platform               100000 non-null  str
 19  region                 80003 non-null   str
dtypes: float64(1), int64(3), str(16)
memory usage: 45.7 MB

In [5]:
print(df.columns.tolist())

['ticket_id', 'created_at', 'customer_id', 'customer_segment', 'channel', 'product_area', 'issue_type', 'priority', 'status', 'sla_plan', 'initial_message', 'agent_first_reply', 'resolution_summary', 'resolution_time_hours', 'reopened', 'customer_sentiment', 'csat_score', 'has_attachment', 'platform', 'region']

In [6]:
df.sample(10, random_state=42)

,ticket_id,created_at,customer_id,customer_segment,channel,product_area,issue_type,priority,status,sla_plan,initial_message,agent_first_reply,resolution_summary,resolution_time_hours,reopened,customer_sentiment,csat_score,has_attachment,platform,region
75721,TCKT_075722,2024-02-02T23:07:49,CUST_03968,non_profit,phone_transcript,notifications,other,high,resolved,standard,I need help but I'm not sure which category th...,Thanks for contacting support. We are prioriti...,Provided general guidance and confirmed the is...,6.47,0,neutral,4,0,web,LATAM
80184,TCKT_080185,2025-11-16T19:07:23,CUST_05746,individual,in_app,login_auth,account_access,urgent,resolved,standard,My account was locked after multiple failed lo...,Sorry to hear you're having trouble accessing ...,Reset account credentials and confirmed succes...,5.10,0,neutral,4,0,android,MEA
19864,TCKT_019865,2025-12-02T22:15:37,CUST_04592,small_business,phone_transcript,api_integration,account_access,low,resolved,platinum,I cannot log in; the system says my password i...,Sorry to hear you're having trouble accessing ...,Reset account credentials and confirmed succes...,49.80,0,negative,2,1,web,MEA
76699,TCKT_076700,2024-06-22T04:06:43,CUST_04204,individual,chat,data_export,bug,low,resolved,standard,I am seeing an error message when I click on d...,Thanks for reporting this bug. We will look in...,Patched the bug and deployed a fix to production.,49.33,0,neutral,0,0,api_client,EU
92991,TCKT_092992,2024-08-16T03:33:46,CUST_03044,enterprise,web_form,mobile_app,account_access,low,on_hold,standard,My 2FA code is not working when I try to sign in.,Sorry to hear you're having trouble accessing ...,NaN,NaN,0,positive,5,0,ios,MEA
76434,TCKT_076435,2025-11-15T17:45:27,CUST_06456,education,phone_transcript,billing,bug,low,in_progress,gold,The billing feature is not saving my changes.,Thanks for reporting this bug. We will look in...,NaN,NaN,0,positive,5,1,android,EU
84004,TCKT_084005,2023-09-11T01:47:28,CUST_08153,education,chat,api_integration,account_access,high,open,standard,I cannot log in; the system says my password i...,Sorry to hear you're having trouble accessing ...,NaN,NaN,0,negative,2,0,api_client,MEA
80917,TCKT_080918,2023-04-16T17:21:33,CUST_00534,non_profit,web_form,mobile_app,other,low,closed_no_action,gold,I need help but I'm not sure which category th...,Thanks for contacting support. We will look in...,Ticket closed without further action after no ...,142.77,0,neutral,0,1,web,APAC
60767,TCKT_060768,2023-11-17T04:53:26,CUST_02880,enterprise,web_form,data_export,feature_request,high,resolved,gold,Can you add an option to customize data export?,Thanks for your feature suggestion. We are pri...,Captured the request and added it to the produ...,2.24,0,positive,4,0,desktop_app,MEA
50074,TCKT_050075,2024-12-28T06:45:17,CUST_09710,small_business,in_app,api_integration,billing_problem,urgent,resolved,standard,I downgraded my plan but I am still being bill...,Thanks for reaching out about the billing issu...,Adjusted the invoice and issued a refund where...,3.56,1,very_positive,5,1,ios,EU

In [7]:
df.isnull().sum().sort_values(ascending=False)

resolution_summary       39887
resolution_time_hours    39887
region                   19997
ticket_id                    0
customer_segment             0
customer_id                  0
created_at                   0
channel                      0
status                       0
product_area                 0
issue_type                   0
priority                     0
agent_first_reply            0
initial_message              0
sla_plan                     0
reopened                     0
customer_sentiment           0
csat_score                   0
has_attachment               0
platform                     0
dtype: int64

In [8]:
df.isnull().sum()

ticket_id                    0
created_at                   0
customer_id                  0
customer_segment             0
channel                      0
product_area                 0
issue_type                   0
priority                     0
status                       0
sla_plan                     0
initial_message              0
agent_first_reply            0
resolution_summary       39887
resolution_time_hours    39887
reopened                     0
customer_sentiment           0
csat_score                   0
has_attachment               0
platform                     0
region                   19997
dtype: int64

In [9]:
df["resolution_time_hours"].describe()

count    60113.000000
mean        45.013123
std         49.202797
min          0.110000
25%         14.880000
50%         29.910000
75%         51.660000
max        239.960000
Name: resolution_time_hours, dtype: float64

In [10]:
for text in df["initial_message"].sample(5, random_state=42):
    print("="*80)
    print(text)

================================================================================
I need help but I'm not sure which category this fits in.
================================================================================
My account was locked after multiple failed login attempts.
================================================================================
I cannot log in; the system says my password is incorrect.
================================================================================
I am seeing an error message when I click on data export.
================================================================================
My 2FA code is not working when I try to sign in.