In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [2]:
df = pd.read_csv("../data/processed/clean_customer_support_dataset.csv")

print(df.shape)

df.head()

(100000, 23)

,ticket_id,created_at,customer_id,customer_segment,channel,product_area,issue_type,priority,status,sla_plan,initial_message,agent_first_reply,resolution_summary,resolution_time_hours,reopened,customer_sentiment,csat_score,has_attachment,platform,region,message_length,word_count,is_resolved
0,TCKT_000001,2024-01-31 05:14:27,CUST_00861,individual,email,data_export,account_access,low,resolved,standard,i cannot log in the system says my password i...,sorry to hear you re having trouble accessing ...,reset account credentials and confirmed succes...,36.53,0,very_negative,1,0,android,EU,58,11,1
1,TCKT_000002,2024-10-20 06:15:49,CUST_00770,individual,in_app,billing,security_concern,medium,closed_no_action,standard,i noticed a suspicious login on my account.,we take security very seriously. our team is r...,ticket closed without further action after no ...,238.32,0,neutral,3,0,web,Unknown,43,8,1
2,TCKT_000003,2024-06-18 21:35:54,CUST_02559,small_business,chat,api_integration,bug,low,in_progress,standard,the api integration feature is not saving my c...,thanks for reporting this bug. we will look in...,NaN,NaN,0,neutral,3,0,android,MEA,53,9,0
3,TCKT_000004,2025-12-25 15:59:52,CUST_03557,education,chat,analytics_dashboard,account_access,medium,in_progress,standard,i cannot log in the system says my password i...,sorry to hear you re having trouble accessing ...,NaN,NaN,0,positive,5,1,android,LATAM,58,11,0
4,TCKT_000005,2023-08-27 16:08:33,CUST_09556,enterprise,phone_transcript,login_auth,billing_problem,low,resolved,gold,my invoice amount is incorrect compared to the...,thanks for reaching out about the billing issu...,adjusted the invoice and issued a refund where...,61.32,0,very_negative,2,0,web,Unknown,63,11,1

In [3]:
issue_df = df[
    [
        "initial_message",
        "issue_type"
    ]
].copy()

In [4]:
issue_df.columns = [
    "text",
    "label"
]

In [5]:
issue_df = issue_df.dropna()

In [6]:
issue_df = issue_df.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

In [7]:
issue_df.head()

                                                text           label
0  i need help but i m not sure which category th...           other
1  my account was locked after multiple failed lo...  account_access
2  i cannot log in  the system says my password i...  account_access
3  i am seeing an error message when i click on d...             bug
4  my 2fa code is not working when i try to sign in.  account_access

In [8]:
priority_df = df[
    [
        "initial_message",
        "priority"
    ]
].copy()

In [9]:
priority_df.columns = [
    "text",
    "label"
]

In [10]:
priority_df = priority_df.dropna()

In [11]:
priority_df = priority_df.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

In [12]:
priority_df.head()

                                                text   label
0  i need help but i m not sure which category th...    high
1  my account was locked after multiple failed lo...  urgent
2  i cannot log in  the system says my password i...     low
3  i am seeing an error message when i click on d...     low
4  my 2fa code is not working when i try to sign in.     low

In [13]:
regression_df = df[
    df["is_resolved"] == 1
].copy()

In [14]:
regression_df = regression_df[
    [
        "issue_type",
        "priority",
        "customer_segment",
        "channel",
        "platform",
        "region",
        "sla_plan",
        "reopened",
        "has_attachment",
        "message_length",
        "word_count",
        "resolution_time_hours"
    ]
]

In [15]:
print(regression_df.shape)

regression_df.head()

(60113, 12)

,issue_type,priority,customer_segment,channel,platform,region,sla_plan,reopened,has_attachment,message_length,word_count,resolution_time_hours
0,account_access,low,individual,email,android,EU,standard,0,0,58,11,36.53
1,security_concern,medium,individual,in_app,web,Unknown,standard,0,0,43,8,238.32
4,billing_problem,low,enterprise,phone_transcript,web,Unknown,gold,0,0,63,11,61.32
5,performance,low,education,email,ios,Unknown,gold,0,0,48,9,226.93
6,security_concern,urgent,education,in_app,api_client,APAC,gold,0,1,43,8,4.36

In [16]:
retrieval_df = df[
    [
        "initial_message",
        "agent_first_reply",
        "resolution_summary",
        "issue_type",
        "priority"
    ]
].copy()

In [17]:
retrieval_df = retrieval_df.dropna(
    subset=["resolution_summary"]
)

In [18]:
retrieval_df = retrieval_df.reset_index(drop=True)

In [19]:
retrieval_df.head()

,initial_message,agent_first_reply,resolution_summary,issue_type,priority
0,i cannot log in the system says my password i...,sorry to hear you re having trouble accessing ...,reset account credentials and confirmed succes...,account_access,low
1,i noticed a suspicious login on my account.,we take security very seriously. our team is r...,ticket closed without further action after no ...,security_concern,medium
2,my invoice amount is incorrect compared to the...,thanks for reaching out about the billing issu...,adjusted the invoice and issued a refund where...,billing_problem,low
3,queries in the mobile app module are timing out.,we understand performance issues can be frustr...,ticket closed without further action after no ...,performance,low
4,i noticed a suspicious login on my account.,we take security very seriously. this has been...,"investigated logs, mitigated the issue, and up...",security_concern,urgent

In [20]:
issue_df.to_csv(
    "../data/processed/issue_classification.csv",
    index=False
)

priority_df.to_csv(
    "../data/processed/priority_prediction.csv",
    index=False
)

regression_df.to_csv(
    "../data/processed/regression_dataset.csv",
    index=False
)

retrieval_df.to_csv(
    "../data/processed/retrieval_dataset.csv",
    index=False
)

print("All AI datasets saved successfully!")

All AI datasets saved successfully!

In [21]:
copilot_df = df[
    [
        "ticket_id",
        "initial_message",
        "issue_type",
        "priority",
        "resolution_summary",
        "resolution_time_hours",
        "customer_sentiment"
    ]
].copy()

In [22]:
copilot_df.to_csv(
    "../data/processed/copilot_demo_dataset.csv",
    index=False
)

In [27]:
print(issue_df["label"].unique())

<ArrowStringArray>
[           'other',   'account_access',              'bug',
  'feature_request',  'billing_problem', 'security_concern',
           'how_to',      'performance']
Length: 8, dtype: str